mkw-sp/mkw-sp

payload/game/ui/TitlePage.c
The updated check will also detect if the Gecko Codehandler is present in memory on a Wii console.
=> Improve Gecko Codehandler detection

configure.py
Not everyone has python installed as `python` (mine is `py` for example), this pull request changes ninja to use the python executable used to run configure.py instead of just `python`
=> Support other python names

configure.py, payload/egg/core/eggColorFader.c, symbols.txt
Drastically reduces (more than halves) loading times on Dolphin, assuming non-toaster hardware.
Closes #157
=> Optimization: Uncap emulation speed during loading sequences

configure.py, payload/revolution/os/OSMemory.S, symbols.txt
These changes will have no effect until the patcher runs before the '.dol' module.
=> Disable code execution in the MEM2 region

payload/game/system/Yaz.c
Increases compression speed by dismissing matches that aren't at least longer than the current longest match.
Addresses [#170](https://github.com/stblr/mkw-sp/issues/170)
=> Improve compression speed.

fuzz/tests.cpp, include/Common.S, payload/egg/core/eggSystem.c, payload/game/gfx/Camera.S, payload/game/kart/KartObjectManager.c, payload/game/system/Console.c, payload/game/system/Console.h, payload/game/system/SaveManager.S, payload/game/system/SaveManager.c, payload/game/system/SaveManager.h, payload/game/ui/GhostManagerPage.c, payload/game/ui/LicenseSelectButton.c, payload/game/ui/LicenseSettingsPage.c, payload/game/ui/Page.c, payload/game/ui/TimeAttackRulesPage.c, payload/game/ui/ctrl/CtrlRace2DMap.S, payload/game/ui/ctrl/CtrlRaceBase.c, payload/game/ui/ctrl/CtrlRaceInputDisplay.c, payload/game/ui/ctrl/CtrlRaceNameBalloon.S, payload/game/ui/ctrl/CtrlRaceNameBalloon.c, payload/game/ui/page/DriftSelectPage.S, payload/game/ui/page/TopMenuPage.c, payload/revolution/os/OSError.c, payload/sp/BaseSettings.c, payload/sp/BaseSettings.h, payload/sp/ClientSettings.c, payload/sp/ClientSettings.h, payload/sp/HexParser.h
Syncs settings with `config.ini` on the SD card and adds a `/set` debug command.
/set DriftMod Yes
```
[BaseSettings.c:18] Unknown key *::DriftMod
[BaseSettings.c:19] Expected one of:
[BaseSettings.c:30] DriftMode HudLabels FOV MapIcons Class GhostSorting TagVisibility TagContent SolidGhosts PageTransitions InputDisplay GhostSound 
```
/set DriftMode Yes
```
[BaseSettings.c:44] Unknown value "Yes" for Race::DriftMode
[BaseSettings.c:46] Expected one of:
[BaseSettings.c:48] - Manual (0)
[BaseSettings.c:48] - Auto (1)
```
/set DriftMode Manual
```
[BaseSettings.c:52] Setting Race::DriftMode to Manual (0)
```
=> Integrate settings, /set command

payload/revolution/os/OSMemory.S, payload/revolution/os/OSMemory.c, payload/revolution/os/OSMemory.h, payload/sp/Payload.cc, symbols.txt
This commit rewrites the function that is responsible for marking the `MEM2` memory region as non-executable.
=> Rewrite a code execution prevention function

payload/game/ui/FriendRoomPage.cc
This also replaces the `DestroyInstance` calls with `RoomManager`'s virtual function.
=> Prevent non-hosts from seeing "Close Room" button

configure.py, payload/platform/guard.c
C++11 guarantees function static variables are threadsafe; these helpers are the Itanium ABI's implementation detail. For now, just disable interrupts during initialization sequences.
=> Implement __cxa_guard_acquire, __cxa_guard_release

payload/game/obj/ObjEffect.S
This check prevents an out-of-bounds write from occurring if an invalid KCL bit field is detected.
=> Prevent an out-of-bounds write from occurring

assets/message/MenuSP_E.bmg.json5, assets/message/MenuSP_U.bmg.json5, payload/sp/settings/ClientSettings.cc
- Added newlines to some of the speedometer option descriptions
- Added a new line to the "all" item music option description
- Performance overlay option moved to the "debug overlay" page, and given the "display/don't display" text
=> Settings Clean Up

payload/game/ui/ctrl/CtrlRaceInputDisplay.cc, payload/sp/settings/ClientSettings.cc
Fixes #501.
This also fixes the CC settings I broke during the battle mode PR, as I had mixed up message IDs.
=> Fix DPad input display in mirror mode

payload/game/ui/RandomMatchingPage.cc, payload/game/ui/RandomMatchingPage.hh, payload/revolution/es.c, payload/revolution/es.h, protobuf/Matchmaking.options, protobuf/Matchmaking.proto, tools/matchmaking/Cargo.toml, tools/matchmaking/migrations/20230203184635_device-id.sql, tools/matchmaking/sqlx-data.json, tools/matchmaking/src/tcp_forward.rs
This implements the required IOS call to fetch the device ID, then sends this information to the matchmaking server if it is not the default dolphin ID.
On the server side, it adds a migration to the DB which sets up the schema better, to allow for user creation to actually occur (this was untested previously).
This PR does not verify if the console is lying about it's device ID, and is a foundation for this verification to be built on by someone other than me.
=> Implement unverified device ID logins

assets/message/MenuSP_U.bmg.json5, configure.py, payload/game/system/GameScene.cc, payload/game/system/GameScene.hh, payload/sp/settings/ClientSettings.cc, payload/sp/settings/ClientSettings.hh, symbols.txt
Replaces the setFramerate setting to allow users to either stay to vanilla, force 60fps, or force 30fps.
Resolves #546
=> Implement FPS Mode setting

payload/egg/core/eggSystem.cc, payload/game/ui/PageId.hh, payload/game/ui/Section.cc, payload/game/ui/Section.hh
Adds a new command to the command system to dump information about the UI system, specifically current section, active pages, and optionally loaded pages.
=> Add /ui_info command

assets/message/MenuSP_U.bmg.json5, payload/game/ui/OnlineTopPage.cc, payload/game/ui/OnlineTopPage.hh
This properly stubs the OnlineTopPage track pack and friends buttons while further development is done.
=> Stub OnlineTopPage buttons in a more user friendly way

payload/game/kart/KartSaveState.cc, payload/game/kart/KartSaveState.hh, payload/sp/SaveStateManager.cc, payload/sp/SaveStateManager.hh
Changes `KartSaveState`'s constructor to require the arguments to create a save state, avoiding the possibility of invalid junk state to be handled. This then uses std::optional in `SaveStateManager` to defer construction until the first save state is created.
=> Avoid constructing invalid KartSaveState

configure.py
For some god awful reason, this works on Linux and not Windows. Due to the lack of Windows CI, this caused #594 to break Windows builds (not that anyone should care).
=> Fix Windows builds

configure.py
Currently, on python versions less than 3.10, we get an ugly error when trying to use `glob` with `root_dir`, this cleans this up to just a basic error. This also adds a warning for using pypy, which currently isn't possible to hit, but may be useful in the future.
=> Configure: Add nicer errors and warnings

payload/game/ui/MultiTopPage.cc, payload/game/ui/OnlineConnectionManagerPage.cc, payload/game/ui/OnlineModeSelectPage.cc, payload/game/ui/OnlineTopPage.cc, payload/game/ui/RandomMatchingPage.cc, payload/game/ui/RandomMatchingPage.hh, payload/game/ui/Section.cc, payload/game/ui/Section.hh, payload/game/ui/SingleTopPage.cc, payload/game/util/Registry.cc
In my infinite wisdom, as I added pages, I added includes directly to `Section.hh`, instead of using a forward declaration as I didn't understand that at the time. This PR reduces the amount of steps ninja reports from `160` when modifying `BattleModeSelectPage.hh` to `60`...
=> Fix certain pages requiring entire UI recompile

payload/game/ui/OnlineConnectionManagerPage.cc, payload/game/ui/OnlineConnectionManagerPage.hh
This PR closes #606, as the client automatically disconnects from matchmaking when transitioning out of the online section, meaning the page (and therefore `AsyncSocket` dtor) is called correctly.
=> Remove destructor override from OnlineConnectionManagerPage

loader/Start.S
Allows lld to link the loader, as it errors for pc relative relocs in non-allocatable sections. Other flags are included for completeness.
=> Set section flags for the first section in Start.S

.github/workflows/build_sp.yml, README.md, configure.py
This PR adds a `--default-targets` argument to the `configure.py` script, which defaults to only build the `test` target. This speeds up compile time by 2x due to having to only compile the `test` target, and avoiding the `debug` target which currently is too large to launch on console.
=> Make debug builds optional

common/IOS.cc, fuzz/tests.cpp, include/Common.S, include/Common.h, include/Common.hh, payload/sp/Bytes.h, payload/sp/Commands.h, payload/sp/Host.h, payload/sp/security/PageTable.cc
This removes unused functions/defines in `include`, and moves items which are only used once into the files they are only used.
Further cleanup has been tested, but doesn't improve compile time at all and causes a lot of churn.
=> Cleanup common files

payload/egg/core/eggSystem.c, payload/game/item/ItemDirector.h, payload/game/kart/KartSaveState.cc, payload/game/kart/KartSaveState.hh, payload/sp/SaveStateManager.cc
This saves item state in KartSaveState, allowing for (as an example) practicing shortcuts that need shrooms without needing to use `/i`.
=> Savestates: Include Item state in KartSaveState

payload/revolution/os.h, payload/revolution/os/OSError.cc, payload/sp/Payload.cc, payload/sp/storage/LogFile.cc, payload/sp/storage/LogFile.h, payload/sp/storage/LogFile.hh
This removes the unnecessary pass through `extern "C"`
=> Remove LogFile.h

.github/workflows/build_sp.yml, .gitignore, README.md, build.py
This prevents issues of the `build.ninja` file becoming out of sync with reality by making `build.ninja` entirely temporary using the builtin `tempfile` library, then passing the path to this temporary file directly to `ninja`. This responsiblity change also allows for more complex logic to be built around the ninja invokation, since we control it.
For manual inspection of the resulting temporary file, `--dry` has been added to `build.py` which will produce the `build.ninja` in the current directory, although this will not be used for builds.
One issue that could arise is that people continue to run `ninja` with versions of `build.ninja` from before this change, although that should pretty quickly break and we can just tell them to use `build.py`.
=> Rename configure.py -> build.py and make responsible for invoking ninja 

assets/message/MenuSP_U.bmg.json5, payload/game/system/RaceConfig.cc, payload/game/system/RaceConfig.hh, payload/game/ui/MultiTopPage.cc, payload/game/ui/PageId.hh, payload/game/ui/SingleTopPage.cc, payload/sp/settings/ClientSettings.cc, payload/sp/settings/ClientSettings.hh
This re-adds the settings from vanilla that were missing from the new settings menu, which closes #519.
I have no idea how to test these work, but I can't imagine how they would not.
=> Re-add missing settings

payload/game/kart/KartBoost.hh, payload/game/kart/KartMove.hh, payload/game/kart/KartSaveState.cc, payload/game/kart/KartSaveState.hh, payload/game/kart/KartTire.hh, payload/game/kart/VehiclePhysics.hh, symbols.txt
This reimplements `KartSaveState` using a cleaner design, storing the minimum amount of data instead of trying to store everything (which contains pointers).
I've tested this doesn't store any pointers by moving `SaveStateManager` to static memory, then simply not resetting the `KartSaveState` when reloading the scene, and it works without crashing.
I could remove the headers added by `KartSaveState`, but they could be useful for future development, so opinions are wanted.
Closes #710 as the implementation is no longer such a hack.
=> Reimplement KartSaveState cleaner

payload/game/ui/GlobalContext.cc, payload/game/ui/GlobalContext.hh, payload/game/ui/MultiTopPage.cc, payload/game/ui/SingleTopPage.cc, payload/sp/settings/ClientSettings.cc, payload/sp/settings/ClientSettings.hh
Part of the fix for #667, undoes the regression made by adding the new settings menu, but does not implement further filtering due to added complexity.
=> Implement vanilla vehicle restrictions

payload/game/effect/Effect.S, payload/game/item/ItemObjKouraAka.S, payload/game/item/ItemObjKouraAo.S, payload/game/item/ItemObjKouraMidori.S, payload/game/kart/KartMove.S, payload/game/kart/KartObjectManager.cc, payload/game/kart/KartObjectManager.hh, payload/game/kart/KartParam.S, payload/game/kart/KartSub.S, payload/game/sound/Snd.S, payload/game/system/InputManager.S, payload/game/ui/AwardPage.cc, payload/game/ui/ctrl/CtrlRaceInputDisplay.cc, payload/game/ui/page/DemoPage.cc, payload/game/util/Input.S, payload/sp/SaveStateManager.cc, symbols.txt
Closes #747.
I accidentally removed the speedModIsEnabled setting in #675, this PR fixes that and uses the Scenario is200cc flag over the global wherever possible.
=> Fix 200cc brake drifting

payload/game/kart/KartBullet.hh, payload/game/kart/KartObjectProxy.hh, payload/game/kart/KartSaveState.cc, payload/game/kart/KartSaveState.hh, payload/game/kart/VehiclePhysics.hh, symbols.txt
Syncs buillets by just calling the activate and cancel methods on KartBullet. From quick testing, this works for `bullet -> not` and `not -> bullet` but goes in the wrong direction for a short time before recalculating for `bullet -> bullet`.
=> Savestates: Sync more bullet state

include/Common.h
If we want to keep it, this could allow us to delete a bunch of .C files and move them into their corresponding C++ source file.
=> Fix legacy `PATCH_BL` for C++

payload/nw4r/lyt/lyt_GroupContainer.cc
This was useful in discovering a mislabled `pane` field is actually a GroupContainer name and should help make the UI system more friendly to work with.
=> Add assertion to GroupContainer_FindGroupByName

payload/game/ui/Page.h
This was still used after #689 due to `KartObjectManager` and `RacePage`, but now can be safely removed.
=> Remove now unused Page.h

.clang-format
This option existing in the config seems to cause clang-format 16 to error with
```
.clang-format:9:24: error: not a mapping
AlignTrailingComments: True
^~~~
Error reading .clang-format: Invalid argument
```
=> Remove AlignTrailingComments format option

payload/nw4r/g3d/g3dResFile.S
This check was causing https://ct.wiimm.de/i/5113 to fail to load on SP, even though it loads completely fine with the check removed.
=> Remove ResFile check causing false positive bugcheck

build.py
We rely on gcc extensions and cannot use clang/a different compiler for these tasks.
=> Explicitly use GCC for asm,incbin,ld

payload/sp/FixedString.hh
This fixes the problem of `Common.h` being included without `extern "C"`, meaning calls to functions like `panic` including C++ name mangling and therefore failing.
=> Fix FixedString's includes

payload/sp/ExceptionSyms.cc
This also corrects the position of the `__cxa_pure_virtual` symbol.
=> Add more symbols for STL exception handling

payload/game/README.md, payload/game/host_system/README.md, payload/platform/README.md, payload/sp/README.md
Start off some basic documentation work to help new contributors or existing contributors understand new systems. These READMEs are not intended for deep technical explaination, simply a quick overview to show what to expect in said folder.
=> Add some initial basic READMEs for different folders in SP

common/ES.hh, common/FS.hh, include/Common.hh, loader/Apploader.hh, loader/Dol.hh, payload/game/system/GhostFile.hh, payload/game/system/RaceConfig.hh, payload/game/ui/MultiTeamSelectPage.hh, payload/game/ui/ScrollBar.hh, payload/sp/Channel.cc, payload/sp/CircularBuffer.hh, payload/sp/CourseDatabase.hh, payload/sp/Exchange.hh, payload/sp/ItemCommand.hh, payload/sp/MapFile.cc, payload/sp/MapFile.hh, payload/sp/SaveStateManager.hh, payload/sp/Update.hh, payload/sp/YAZDecoder.hh, payload/sp/net/SyncSocket.hh, payload/sp/net/UnreliableSocket.hh, payload/sp/settings/IniReader.hh, payload/sp/storage/Storage.hh, stub/Archive.hh, stub/LZMA.hh
Turns out this actually reduces line count because we get to remove all the `#include <optional>`
=> Implement a Rust-like macro for TRY on std::optional

tools/updateserver/Cargo.toml
This forces updateserver's argon2 dependency to always be built with optimizations, preventing insanely slow startup times due to password hashing.
=> Fix startup time of debug build updateserver

payload/sp/storage/FATStorage.cc
This one feels kind of funny because. It took me 18 tries for mkw-sp to pick USB instead of SD 5 times. Of course with this single line edit, it would mount my USB a grand total of 0 times out of those same 18. However i'm just surprised that it mounted my USB only... 5 times. I guess it's just Dolphin
=> Try mount SD first(?)

payload/game/system/SaveManager.cc
failed if the user had no saves :P
```cc
// SaveManager::initSPSave()
if (oldLicenseExists /* false */ ) { SP::Storage::CreateDir(/* ... */) }
```
```cc
// SaveManager::saveSPSave()
if (!SP::Storage::WriteFile(path, /* ... */) { // <-- false because /mkw-sp/licenses/ does not exist
```
=> Create /mkw-sp/licenses/ earlier on
