mkw-sp/mkw-sp

.github/workflows/build.yml

Solves #53 
Adds an action for compiling.

Add github actions for building

---

configure.py
payload/game/ui/Map2DRenderer.c
payload/revolution/gx/GXEnum.h
symbols.txt

This PR integrates my Colored Minimap code directly into mkw-sp.
Screenshot: *DS Luigi's Mansion (Tock) features the Mario Kart 7 minimap.*

CT: Support non-grayscale minimaps (resolves #80)

---

assets/message/Menu_E.bmg.json5
assets/message/Menu_F.bmg.json5
assets/message/Menu_G.bmg.json5
assets/message/Menu_I.bmg.json5
assets/message/Menu_J.bmg.json5
assets/message/Menu_K.bmg.json5
assets/message/Menu_M.bmg.json5
assets/message/Menu_Q.bmg.json5
assets/message/Menu_S.bmg.json5
assets/message/Menu_U.bmg.json5

All languages have the string in English
Solves #89

Change BMG 0x7eb for it to match the menu

---

configure.py
include/Common.h
payload/egg/core/eggSystem.c
payload/revolution/ios.h
payload/sp/Keyboard.cpp
payload/sp/Keyboard.h
symbols.txt

Adds basic USB keyboard interaction for debugging.
Screenshot:

Basic keyboard support

---

payload/game/ui/SectionManager.c
payload/game/ui/SectionManager.h

Scene transitions now fade to white (as opposed to black).
Footage: https://www.youtube.com/watch?v=1Y6H7YzKFm4

UI: Fade to white

---

payload/game/ui/page/RaceMenuPage.S
payload/game/ui/page/RaceMenuPage.c

This will allow us to add additional buttons to pause menus without hacks. First step toward #130.

Refactor RaceMenuPage

---

payload/game/ui/LicenseSelectPage.c
payload/game/ui/LicenseSettingsPage.c
payload/game/ui/Page.h
payload/game/ui/TimeAttackGhostListPage.c
payload/game/ui/TimeAttackRulesPage.c
payload/game/ui/TypeInfo.h
symbols.txt

Add Page RTTI helpers

---

configure.py
fetch.py
payload/egg/core/eggSystem.c
payload/game/host_system/RkSystem.S
payload/nw4r/db/dbException.c
payload/sp/Host.c
payload/sp/Host.h
payload/sp/Version.h
symbols.txt

Example output: `0.1.1 (Release) b7171ee (Built Feb 15 2022 at 18:58:02, 10.2.0)`

Add MKW-SP info to NW4R Exception Handler

---

include/Common.h

Probably will take effect in a month

Don't include full filepath in SP_LOG prefix

---

include/Common.h
payload/sp/Bytes.h
payload/sp/NetStorageClient.c

This will allow for fuzzing/better debugging.

NetStorageClient: Support compiling on PC

---

.gitignore
fuzz/CMakeLists.txt
fuzz/CMakeSettings.json
fuzz/tests.cpp
payload/game/host_system/Payload.c
payload/game/system/SaveManager.c
payload/sp/Emulator/NetEmuWin.cpp
payload/sp/Emulator/OSEmu.cpp
payload/sp/FatStorage.c
payload/sp/Net.c
payload/sp/Net.h
payload/sp/NetStorage.c
payload/sp/NetStorageClient.c
payload/sp/Storage.c
payload/sp/Storage.h
payload/sp/WfsStorage.c
payload/sp/Yaz.h

Output
```
--------------------------------
MKW-SP v0.1.4 (Release) REV <GIT ?>
Region: PAL, System: Windows
Built Mar  7 2022 at 02:57:14, Clang 12.0.0
--------------------------------
[tests.cpp:52] BUF: Yaz0
[tests.cpp:59] Encoded size: 4471519
[tests.cpp:62] Decoded size: 6847040
[tests.cpp:72] BUF: U¬8-
[tests.cpp:75] Compressing...
[tests.cpp:83] Compressed to 3550298 bytes
[tests.cpp:90] (Took 12114 ms)
[tests.cpp:93] Decompressing...
[tests.cpp:98] Checking...
[tests.cpp:101] Recompression worked? YES
```

Add Net/OS emulator, tests.cpp

---

.gitignore
fuzz/CMakeLists.txt
include/Common.h
payload/revolution/dvd.h
payload/revolution/os.h
payload/sp/Bytes.h
payload/sp/Emulator/NetEmu.cpp
payload/sp/Host.c
payload/sp/NetStorageClient.c
payload/sp/Storage.h

tests.cpp: Support Linux/Apple

---

payload/game/ui/ctrl/CtrlRaceInputDisplay.c

InputDisplay: Mirror inputs on Mirror Mode

---

fuzz/NetStorageServer.py
fuzz/tests.cpp
payload/sp/NetStorageClient.c
payload/sp/NetStorageClient.h

NetStorageClient: Add JSON API

---

payload/game/ui/Font.S
payload/game/ui/Font.h
payload/nw4r/ut/ut_resFont.h
payload/revolution/gx/GXStruct.h
symbols.txt

Add GlyphRenderer, RKFontGlyphQuad, etc to Font.h

---

payload/egg/core/eggSystem.c
payload/game/item/ItemDirector.h
payload/game/system/RaceConfig.h
symbols.txt

`/i [item] [qty|0=STICKY]`
`/i`: Clear the player's item
`/i 6`: Give the player 1 bob-omb
`/i 5 2`: Give the player 2 mushrooms
`/i 5 -2`: Give the player permanent 2 mushrooms

Add /i command

---

payload/egg/core/eggSystem.c
payload/game/system/SaveManager.h
payload/game/ui/SectionManager.h
payload/game/ui/TimeAttackRulesPage.c
payload/nw4r/lyt/lyt_pane.h
payload/sp/IOSDolphin.h
payload/sp/IOSKeyboard.h
payload/sp/TypingBuffer.h

`/section <section_id>`
`/section 3`: Returns to the Wii menu
`/section 74`: Select a course to TT (requires the game to already be in MenuSingle).

Add /section command

---

www/features.markdown

Updates the Features list on the website to include the Custom Discord Status feature.

Add Custom Discord Status in Features list

---

include/Common.S
payload/revolution/os/OSMemory.S
payload/revolution/os/OSMemory.c
payload/revolution/os/OSMemory.h
payload/sp/Payload.cc
payload/sp/Payload.h
port.py

Dynamically protect the executable sections of the payload

---

payload/platform/string.c
symbols.txt

Aims to resolve issue https://github.com/stblr/mkw-sp/issues/149.

Use the optimized version of the function 'memcpy'

---

payload/platform/string.c
payload/revolution/net/NETMisc.h
symbols.txt

Use the optimized version of the function 'memset'

---

.clang-format
payload/egg/core/eggSceneManager.cc
payload/game/host_system/SystemManager.cc
payload/game/host_system/SystemManager.hh
payload/game/ui/SectionManager.cc
payload/game/ui/SectionManager.hh
payload/sp/IOSDolphin.cc
payload/sp/IOSDolphin.hh

"state" and "details" in `RichPresenceManager::setGameState` would ideally be strings loaded from a BMG file, but I will leave that work for someone else to tackle in another PR.

Expand Discord rich presence to update on section

---

configure.py
loader/Loader.cc
payload/revolution/os/OSThread.S
payload/revolution/start.S
payload/sp/Payload.cc
payload/sp/Payload.h
payload/sp/security/Stack.c
payload/sp/security/Stack.h
port.py
symbols.txt

There is no need to move the main thread's stack once pull request #495 is merged.

Do not move the main thread's stack to the end of MEM1

---

meta/debug.xml
meta/release.xml
meta/test.xml

We got substantial contributions from several new developers and we don't have enough space to put all the names. The online updater also doesn't touch this file.

Update credits in HBC XML

---

configure.py
payload/egg/core/eggThread.cc
payload/egg/core/eggThread.hh
payload/game/system/SaveManager.hh
payload/game/ui/ChannelPage.hh
payload/game/ui/CourseSelectPage.hh
payload/game/ui/StorageBenchmarkPage.hh
payload/game/ui/UpdatePage.hh
payload/revolution/os/OSThread.h
payload/sp/net/Net.cc
payload/sp/storage/DecompLoader.cc
payload/sp/storage/LogFile.cc
payload/sp/storage/NetStorage.hh
payload/sp/storage/Usb.c
symbols.txt

This commit will close issue #446.

Add stack overflow protection

---

tools/gameserver/Cargo.toml
tools/gameserver/src/async_stream.rs
tools/gameserver/src/client.rs
tools/gameserver/src/event.rs
tools/gameserver/src/main.rs
tools/gameserver/src/request.rs
tools/gameserver/src/server.rs

Added support for forwarding the Comment message, while properly adding anyhow, tracing, and documentation for helping the development experience.

gameserver: Implement chat

---

assets/message/MenuSP_U.bmg.json5
payload/game/ui/ctrl/CtrlRaceLap.cc
payload/game/ui/page/RacePage.cc
payload/sp/settings/ClientSettings.cc
payload/sp/settings/ClientSettings.hh

Adds an option to disable the speedometer's rendering.
Closes #527.

Allow disabling of the speedometer

---

configure.py
payload/game/system/BugCheck.c
payload/game/system/FatalScene.c
payload/game/system/FatalScene.h
payload/game/ui/Button.h
payload/game/ui/License.c
payload/game/ui/TitlePage.c
payload/game/ui/TitlePage.h
payload/game/ui/page/MenuPage.h
payload/game/ui/page/TimeAttackSplitsPage.c
payload/game/ui/page/TimeAttackSplitsPage.h
payload/game/ui/page/TopMenuPage.c
payload/game/ui/page/TopMenuPage.h

Completes https://github.com/stblr/mkw-sp/issues/297#issuecomment-1138581747, ideally these replacements should be replaced with C++ replacements but for now, this is the easiest way to get rid of the argument.

Remove usage of -fplan9-extensions

---

.github/workflows/build_sp.yml
configure.py
payload/game/system/MultiDvdArchive.cc
payload/game/ui/FriendMatchingPage.cc
payload/game/ui/OnlineModeSelectPage.cc
payload/game/ui/SingleTopPage.cc
payload/game/ui/VotingBackPage.cc
payload/game/ui/VotingBackPage.hh
payload/game/ui/ctrl/CtrlRaceSpeed.cc
payload/game/ui/page/BattleModeSelectPage.hh
payload/game/ui/page/RaceMenuPage.cc
payload/sp/cs/RoomManager.hh
payload/sp/storage/Sdi.c

Use Werror in CI

---

payload/game/ui/page/DemoPage.cc

Planned to add the bubbles for point display, never ended up doing it, never removed the child count calculation

Fix battle mode after DemoPage patch rewrite

---

payload/game/ui/MultiTopPage.cc

Fix animation direction of MultiTopPage::onBack

---

payload/egg/core/eggSystem.c
payload/egg/core/eggSystem.cc
payload/game/system/SaveManager.cc
payload/game/system/SaveManager.h
payload/sp/Commands.c
payload/sp/Commands.cc
payload/sp/Commands.h
payload/sp/Commands.hh
payload/sp/ItemCommand.c
payload/sp/ItemCommand.h
payload/sp/settings/ClientSettings.h

This untangles the commands from the EGG library, and rewrites them to C++. Should be reviewable commit by commit pretty easily.

Cleanup commands

---

build.py

We should really have some CI for this

Fix Windows building broken by #693

---

payload/game/system/BugCheck.c
payload/game/system/BugCheck.h

These functions were completely unused.

Remove unused bugcheck functionality

---

payload/game/system/BugCheck.c

Swap static variables for out param in BugCheck

---

payload/egg/core/eggExpHeap.hh
payload/game/kart/Kart5c.hh
payload/game/kart/KartSus.hh
payload/game/kart/KartTire.hh
payload/game/kart/PlayerModel.hh
payload/game/obj/ObjManager.h
payload/game/system/RootScene.hh
payload/game/ui/SaveManagerProxy.hh
payload/game/ui/page/TopMenuPage.hh
payload/revolution/gx/GXTexture.h
payload/sp/Rel.hh
tools/tidy/checks/__init__.py
tools/tidy/checks/pragma_once.py

Ensure #pragma once is applied to all headers

---

payload/game/system/RaceConfig.cc
payload/game/system/RaceConfig.hh
payload/game/ui/page/DriftSelectPage.cc
payload/game/ui/page/DriftSelectPage.hh
payload/game/ui/page/MultiDriftSelectPage.cc
payload/game/ui/page/RaceMenuPage.cc
payload/sp/CourseDatabase.cc
payload/sp/CourseDatabase.hh

Part of the fix for #667, implements CourseSelection::Random and CourseSelection::InOrder

Implement ClientSettings::CourseSelection

---

build.py

Drop debug build by default

---

payload/game/system/RaceConfig.cc
payload/game/system/RaceConfig.hh
payload/game/ui/ModelPage.cc
payload/game/ui/ModelPage.hh
payload/game/ui/MultiTopPage.cc
payload/game/ui/SingleTopPage.cc

This de-duplicates the ModelPage logic and player setup code.

Cleanup single and multi top pages

---

assets/message/MenuSP_U.bmg.json5

Reword settings deletion

---

common/IOS.cc
common/IOS.hh
loader/Loader.cc

Do not permit the use of unsupported IOSes

---

loader/Loader.cc

Hoping for no [destructive results](https://wiibrew.org/wiki/Error_003) by telling people to do a Wii system update 😺

help the user install IOS58

---

payload/game/system/SaveManager.cc
payload/game/system/SaveManager.hh

Allows for testing if a course is being My Stuff replaced for Track Packs.

Add SaveManager::isCourseReplaced

---

payload/game/system/GhostFile.cc
payload/game/system/GhostFile.hh
payload/game/system/SaveManager.cc
payload/game/system/SaveManager.hh
payload/sp/ShaUtil.cc
payload/sp/ShaUtil.hh

Implement utils for working with Sha

---

assets/button/anim/common_w010_cup_free.brlan.json5
assets/button/anim/common_w010_cup_fuchi_check_loop.brlan.json5
assets/button/anim/common_w010_cup_text_light_01_ok.brlan.json5
assets/button/anim/common_w010_cup_text_light_01_stop.brlan.json5
assets/button/anim/common_w010_cup_text_light_02_select.brlan.json5
assets/button/anim/common_w010_cup_text_light_02_stop.brlan.json5
assets/message/MenuSP_U.bmg.json5
build.py
payload/game/ui/OnlineConnectionManagerPage.hh
payload/game/ui/OnlineTopPage.cc
payload/game/ui/PackSelectPage.cc

This allow the online UI to load again after #807. It also fixes some other small online UI issues related to track packs.

Fix PackSelectPage online asset issues

---

assets/message/MenuSP_U.bmg.json5

I'm /enby btw 
i wanna be a contributor but idk any code :3

Be more serious in error messages.

---

payload/game/ui/LicenseSelectPage.cc
payload/game/ui/MiiGroup.cc
payload/game/ui/MiiGroup.hh

LicenseSelectPage: Allocate enough space for all 6 potential miis

---

payload/game/ui/CourseSelectPage.cc
payload/game/ui/RandomMatchingPage.cc

I have no idea how this ever worked.

Fix CourseSelectPage when going through matchmaking

---

payload/game/system/SaveManager.cc

Closes https://github.com/mkw-sp/mkw-sp/issues/903. Man i spent up until 1am on this thing

Move licenses to a folder named licenses (..)

---

.github/workflows/build_sp.yml

might be a newer version that works but idrt we care about that

Fix pipeline
